---
version: "3.8"

services:
  app:
    image: ${APP_REGISTRY}/${APP_NAME}:${APP_TAG}
    build:
      cache_from:
        - ${APP_REGISTRY}/${APP_NAME}:${APP_TAG}
      context: .
    environment:
      - APP_ENV
      - APP_NAME
      - APP_REGISTRY
      - APP_TAG
      - APP_USER
    hostname: ${APP_NAME}
    init: true
    user: ${APP_USER}
    volumes:
      # Allow the container to talk to the docker daemon on the host OS
      # so we can use container-structure-test.
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      # Persist home dir content (bash history, caches, etc).
      - home-data:${APP_HOME}
      - .:/app:delegated

volumes:
  home-data: {}
