name: build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # 10am UTC every Monday (weekly security scan)
    - cron: '0 10 * * 1'

env:
  IMAGE_NAME: ghcr.io/gostamp/image-tools

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # pin@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # pin@v2

      - name: Build
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # pin@v3
        with:
          load: true
          context: .
          cache-from: |
            type=gha
            type=registry,ref=${{ env.IMAGE_NAME }}:latest
            type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: |
            type=gha
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Inspect
        run: make inspect

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Scan
        run: make scan

      - name: Upload dockle.sarif
        uses: github/codeql-action/upload-sarif@b2a92eb56d8cb930006a1c6ed86b0782dd8a4297 # pin@v2
        with:
          sarif_file: dockle.sarif

      - name: Upload trivy.sarif
        uses: github/codeql-action/upload-sarif@b2a92eb56d8cb930006a1c6ed86b0782dd8a4297 # pin@v2
        with:
          sarif_file: trivy.sarif
