name: build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # 10am UTC every Monday (weekly security scan)
    - cron: '0 10 * * 1'

env:
  IMAGE_NAME: ghcr.io/gostamp/image-tools

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # pin@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@15c905b16b06416d2086efa066dd8e3a35cc7f98 # pin@v2

      - name: Build
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # pin@v3
        with:
          load: true
          context: .
          cache-from: |
            type=gha
            type=registry,ref=${{ env.IMAGE_NAME }}:latest
            type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: |
            type=gha
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Inspect
        run: make inspect

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Scan
        run: make scan

      - name: Upload dockle.sarif
        uses: github/codeql-action/upload-sarif@3ebbd71c74ef574dbc558c82f70e52732c8b44fe # pin@v2
        with:
          sarif_file: dockle.sarif

      - name: Upload trivy.sarif
        uses: github/codeql-action/upload-sarif@3ebbd71c74ef574dbc558c82f70e52732c8b44fe # pin@v2
        with:
          sarif_file: trivy.sarif
